package seurantakaaviot.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import seurantakaaviot.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2021.04.23 00:17:25 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class DatapisteTest {



  // Generated by ComTest BEGIN
  /** testRekisteroi78 */
  @Test
  public void testRekisteroi78() {    // Datapiste: 78
    Datapiste dat1 = new Datapiste(); 
    assertEquals("From: Datapiste line: 80", 0, dat1.getTunnusNro()); 
    dat1.rekisteroi(); 
    Datapiste dat2 = new Datapiste(); 
    dat2.rekisteroi(); 
    int n1 = dat1.getTunnusNro(); 
    int n2 = dat2.getTunnusNro(); 
    assertEquals("From: Datapiste line: 86", n2-1, n1); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testPaivamaara128 */
  @Test
  public void testPaivamaara128() {    // Datapiste: 128
    Datapiste datapiste = new Datapiste(); 
    assertEquals("From: Datapiste line: 130", true, datapiste.paivamaara().equals("00.00.0000")); 
    datapiste.aseta(1, "31"); 
    assertEquals("From: Datapiste line: 132", true, datapiste.paivamaara().equals("31.00.0000")); 
    datapiste.aseta(2, "12"); 
    assertEquals("From: Datapiste line: 134", true, datapiste.paivamaara().equals("31.12.0000")); 
    datapiste.aseta(3, "2020"); 
    assertEquals("From: Datapiste line: 136", true, datapiste.paivamaara().equals("31.12.2020")); 
  } // Generated by ComTest END
}