package seurantakaaviot.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import seurantakaaviot.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2021.04.23 00:17:38 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class HenkiloTest {



  // Generated by ComTest BEGIN
  /** testRekisteroi69 */
  @Test
  public void testRekisteroi69() {    // Henkilo: 69
    Henkilo aku1 = new Henkilo(); 
    assertEquals("From: Henkilo line: 71", 0, aku1.getTunnusNro()); 
    aku1.rekisteroi(); 
    Henkilo aku2 = new Henkilo(); 
    aku2.rekisteroi(); 
    int n1 = aku1.getTunnusNro(); 
    int n2 = aku2.getTunnusNro(); 
    assertEquals("From: Henkilo line: 77", n2-1, n1); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testToString183 */
  @Test
  public void testToString183() {    // Henkilo: 183
    Henkilo henkilo = new Henkilo(); 
    henkilo.parse("   3  |  Ankka Aku   | 030201-111C"); 
    assertEquals("From: Henkilo line: 186", true, henkilo.toString().startsWith("3|Ankka Aku|030201-111C|"));  // on enemmäkin kuin 3 kenttää, siksi loppu |
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testParse210 */
  @Test
  public void testParse210() {    // Henkilo: 210
    Henkilo henkilo = new Henkilo(); 
    henkilo.parse("   3  |  Ankka Aku   | 030201-111C"); 
    assertEquals("From: Henkilo line: 213", 3, henkilo.getTunnusNro()); 
    assertEquals("From: Henkilo line: 214", true, henkilo.toString().startsWith("3|Ankka Aku|030201-111C|"));  // on enemmäkin kuin 3 kenttää, siksi loppu |
    henkilo.rekisteroi(); 
    int n = henkilo.getTunnusNro(); 
    henkilo.parse(""+(n+20));  // Otetaan merkkijonosta vain tunnusnumero
    henkilo.rekisteroi();  // ja tarkistetaan että seuraavalla kertaa tulee yhtä isompi
    assertEquals("From: Henkilo line: 220", n+20+1, henkilo.getTunnusNro()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** 
   * testClone242 
   * @throws CloneNotSupportedException when error
   */
  @Test
  public void testClone242() throws CloneNotSupportedException {    // Henkilo: 242
    Henkilo henkilo = new Henkilo(); 
    henkilo.parse("   3  |  Ankka Aku   | 123"); 
    Henkilo kopio = henkilo.clone(); 
    assertEquals("From: Henkilo line: 247", henkilo.toString(), kopio.toString()); 
    henkilo.parse("   4  |  Ankka Tupu   | 123"); 
    assertEquals("From: Henkilo line: 249", false, kopio.toString().equals(henkilo.toString())); 
  } // Generated by ComTest END
}