package seurantakaaviot.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import seurantakaaviot.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2021.04.23 00:17:50 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class KaavioTest {



  // Generated by ComTest BEGIN
  /** testRekisteroi97 */
  @Test
  public void testRekisteroi97() {    // Kaavio: 97
    Kaavio kaavio1 = new Kaavio(); 
    assertEquals("From: Kaavio line: 99", 0, kaavio1.getTunnusNro()); 
    kaavio1.rekisteroi(); 
    Kaavio kaavio2 = new Kaavio(); 
    kaavio2.rekisteroi(); 
    int n1 = kaavio1.getTunnusNro(); 
    int n2 = kaavio2.getTunnusNro(); 
    assertEquals("From: Kaavio line: 105", n2-1, n1); 
  } // Generated by ComTest END
}